language: generic
sudo: required
env: SWIFT_VERSION=4.0

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9

install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" 

script:
  - swift test
